### ISSUE TITLE
Problem when build project

### ISSUE THREAD

**Issue by alfongf** [macdonst/push-workshop#1]
I get an error when I try to build the app. I want to run it on a MotoG 3rd generation with Android 5.1.1. I'm using last cordova version (6.0.0) and this is the error I get:

---
- What went wrong:
  A problem occurred configuring root project 'android'.
  > Could not resolve all dependencies for configuration ':_debugCompile'.
  > Could not find any version that matches com.android.support:support-v4:+.

BUILD FAILED
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
     Required by:
         :android:unspecified

> Could not find any version that matches com.android.support:support-v13:23+.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/support/support-v13/maven-metadata.xml
>          https://repo1.maven.org/maven2/com/android/support/support-v13/
>      Required by:
>          :android:unspecified
> Could not find any version that matches com.google.android.gms:play-services-gcm:+.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
>          https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/
>      Required by:
>          :android:unspecified
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
  Total time: 8.76 secs
  ERROR building one of the platforms: Error code 1 for command: cmd with args: /s,/c,"C:\Apps\pgpush\platforms\android\gradlew cdvBuildDebug -b C:\Apps\pgpush\platforms\android\bui
  ld.gradle -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"
  You may not have the required environment or OS to build this project
  Error: Error code 1 for command: cmd with args: /s,/c,"C:\Apps\pgpush\platforms\android\gradlew cdvBuildDebug -b C:\Apps\pgpush\platforms\android\build.gradle -Dorg.gradle.daemon=
  true -Pandroid.useDeprecatedNdk=true"
  ***************************************************************************************

Thanks in advance,

Alfonso

**Comment by macdonst** [comment]
@alfongf here are some instructions on getting your build environment setup correctly on Android. 

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#compilation

If it fixes the problem, please close the issue.

**Comment by alfongf** [comment]
Thanks!! I fixed the problem with these instructions.
