### ISSUE TITLE
google GCM changed to FCM 

### ISSUE THREAD

**Issue by Amalkarunakaran** [macdonst/push-workshop#3]
How we can do it for firebase cloud messaging service ?? Because the google changed its gcm to fcm ???
And by this if we run "gcmService.js" file then it shows an error -

{ multicast_id: 7xxxxxxxxxxxxxxxx00,
  success: 0,
  failure: 1,
  canonical_ids: 0,
  results: [ { error: 'MismatchSenderId' } ] }

Please help me ASAP..

**Comment by tmwebs** [comment]
The same happens to me

**Comment by macdonst** [comment]
I have a FCM branch under the push plugin which I hope to have released by the end of the year.
